git clone git@github.com:baixing/ShanYao.git
git clone git@github.com:baixing/haojing.git
git clone git@github.com:baixing/luoyi-chencang.git
git clone git@github.com:baixing/luoyi-ios.git
git clone git@github.com:baixing/shanyao_nuxt.git
git clone git@github.com:baixing/shanyao_server.git
git clone git@github.com:baixing/luoyi-nest.git
git clone git@github.com:baixing/luoyi-sync.git
git clone git@github.com:baixing/ShanYao-HK.git
git clone git@github.com:baixing/luoyi-fe.git
git clone git@github.com:baixing/luoyi-admin-api.git
git clone git@github.com:baixing/Dudu-Server-SCF.git
git clone git@github.com:baixing/luoyi-admin-fe.git
git clone git@github.com:baixing/ShanYao-Image.git
git clone git@github.com:baixing/DuduCam.git
git clone git@github.com:baixing/chato-service.git
git clone git@github.com:baixing/chrome-plugin-crm.git
git clone git@github.com:baixing/shanyao-android.git
git clone git@github.com:baixing/data-analysis.git
git clone git@github.com:baixing/luoyi-android.git
git clone git@github.com:baixing/longkui-node.git
git clone git@github.com:baixing/chrome-plugin.git
git clone git@github.com:baixing/chato-fe.git
git clone git@github.com:baixing/longkui-server.git
git clone git@github.com:baixing/xunta.git
git clone git@github.com:baixing/syncam-server.git
git clone git@github.com:baixing/syncam-server-uia.git
git clone git@github.com:baixing/duducam-server.git
git clone git@github.com:baixing/SynCam.git
git clone git@github.com:baixing/baixing-uni-mini.git
